name: SurvivalRecipes
version: 1.0
main: masa3mc.survivalrecipes.SurvivalRecipes
api-version: 1.19
authors: [NameKun]
description: This plugin adds the recipes for Survival Server.

commands:
  votecoin:
    permission: votecoin
    usage: /votecoin
